baseurl      = "/"
title        = "My Blog"
languageCode = "en-us"
theme        = "hello-friend-ng"
pagination.pagerSize     = 10



[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # load custom css
    customCSS = ["/css/custom.css"]

  # Subtitle for home
  homeSubtitle = "Test"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true
  
  # Show a global language switcher in the navigation bar
  enableGlobalLanguageMenu = true

  # Metadata mostly used in document's head
  description = "My new homepage or blog"
  keywords = "homepage, blog"
  images = [""]

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Begum Akkas"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

  [languages.en.params]
    subtitle  = "A simple theme for Hugo"

    [languages.en.params.logo]
      logoText = "Begum"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # Menus
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"

  [[menu.main]]
    identifier = "projects"
    name       = "Projects"
    url        = "/projects"

# delete below after referencing
  # and submenus
  #[[menu.main]]
   # identifier  = "parent"
    #name        = "Parent"
    #url         = "/parent"
    #hasChildren = true

  #[[menu.main]]
   # identifier  = "child"
    #name        = "Child"
    #url         = "/parent/child"
    #parent      = "parent"
    #baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

# social icons
[[params.social]]
  name = "<site>"
  url = "<profile_URL>"

# allow rendering of raw html
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
