baseURL      = "/"
title        = "Begum Akkas"
languageCode = "en-us"
theme        = "hello-friend-ng"


[params]
homeSubtitle = "Full-Stack Engineer & UChicago Graduate Student (MSCAPP)"

# load custom css
customCSS = ["/css/custom.css"]

# Show a global language switcher in the navigation bar
enableGlobalLanguageMenu = false

# Metadata mostly used in document's head
description = "My portfolio"

    # logo in the top-left
    [params.logo]
        logoText = "Begum"
        logoHomeLink = "/"

    [params.portrait]
    path = "/images/begumHome.jpeg"
    alt = "Begum Akkas"
    maxWidth = "220px"

    [[params.social]]
    name = "github"
    url = "https://github.com/begumakkas"

    [[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/begumak/"


    # Menus
    [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"

    [[menu.main]]
    identifier = "projects"
    name       = "Projects"
    url        = "/projects"

    [[menu.main]]
    identifier = "connect"
    name       = "Connect"
    url        = "/connect"


    # allow rendering of raw html
    [markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
        unsafe = true
